//! End-to-end hand-written parser fuzz target.
//!
//! Feeds libFuzzer-generated bytes (validated as UTF-8) into
//! `iter_language::parse_to_cst` and asserts that the call returns without
//! panicking or hanging. libFuzzer's own timeout (`-timeout=1`) enforces
//! the hang-free property.

#![no_main]

use libfuzzer_sys::fuzz_target;

fuzz_target!(|data: &[u8]| {
    let Ok(s) = std::str::from_utf8(data) else {
        return;
    };
    let _ = iter_language::parse_to_cst(s);
});
