//! Accept/reject differential fuzz target.
//!
//! Feeds libFuzzer-generated bytes to both the hand-written parser and the
//! pest oracle; any disagreement on the accept/reject verdict panics so
//! libFuzzer records it as a crash.

#![no_main]

use libfuzzer_sys::fuzz_target;
use pest::Parser;
use pest_derive::Parser;

// The canonical grammar lives at `iter_language/grammar/iter.pest`. This
// crate's manifest dir is `iter_language/fuzz`; `pest_derive` resolves
// `#[grammar = "..."]` relative to that, so `../grammar/iter.pest` walks
// one directory up into the parent crate and reaches the spec.
#[derive(Parser)]
#[grammar = "../grammar/iter.pest"]
struct OracleParser;

fn hw_accepts(source: &str) -> bool {
    let (_cst, diag) = iter_language::parse_to_cst(source);
    !diag
        .iter()
        .any(|d| d.severity == iter_language::Severity::Error)
}

fn oracle_accepts(source: &str) -> bool {
    OracleParser::parse(Rule::file, source).is_ok()
}

fuzz_target!(|data: &[u8]| {
    let Ok(s) = std::str::from_utf8(data) else {
        return;
    };
    let hw = hw_accepts(s);
    let oracle = oracle_accepts(s);
    assert_eq!(
        hw, oracle,
        "accept/reject divergence between hand-written and pest oracle on:\n{s}"
    );
});
